// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiNquimtiaGTqVTw8mgDVP-Zdg_UTthpI',
    appId: '1:516526746191:web:79406c073d8dd31ebed83a',
    messagingSenderId: '516526746191',
    projectId: 'atelier4-saad-elbahi-iir5g5',
    authDomain: 'atelier4-saad-elbahi-iir5g5.firebaseapp.com',
    storageBucket: 'atelier4-saad-elbahi-iir5g5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1YQVCHt821VtKI4XB4HE57N51-_agEl4',
    appId: '1:516526746191:android:011dcd2ba0c45eadbed83a',
    messagingSenderId: '516526746191',
    projectId: 'atelier4-saad-elbahi-iir5g5',
    storageBucket: 'atelier4-saad-elbahi-iir5g5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8C2bXxhaw7u6-IWJ0Dj8yj3CDOWLqL3o',
    appId: '1:516526746191:ios:80a6a0526bce8851bed83a',
    messagingSenderId: '516526746191',
    projectId: 'atelier4-saad-elbahi-iir5g5',
    storageBucket: 'atelier4-saad-elbahi-iir5g5.appspot.com',
    iosBundleId: 'com.example.atelier4SElbahiIir5g5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8C2bXxhaw7u6-IWJ0Dj8yj3CDOWLqL3o',
    appId: '1:516526746191:ios:8601c40feb27f4d1bed83a',
    messagingSenderId: '516526746191',
    projectId: 'atelier4-saad-elbahi-iir5g5',
    storageBucket: 'atelier4-saad-elbahi-iir5g5.appspot.com',
    iosBundleId: 'com.example.atelier4SElbahiIir5g5.RunnerTests',
  );
}
